### ISSUE TITLE
Swipe to move page

### ISSUE THREAD

**Issue by vtbeerloverguy** [pipacs/ionic#44] opened 2012-03-29 12:35 UTC
On my nokia C6-01 I can no longer slide the pages around with the touch screen in Ionic v0.6.2.  I see that option available in the settings, but it doesn't work anymore. Changing using the arrows on the status bar works as does using the volume control.  This swipe feature worked in the previous version of Ionic.

**Comment by pipacs** [comment] 2012-03-29 17:05
Duplicate of #42

**Closed as completed by pipacs** 2012-03-29 17:05 UTC
